#!/bin/zsh
open -a XQuartz
open -a Docker
while ! /usr/local/bin/docker ps &> /dev/null
do
open -a Docker
sleep 5
done
while ! [ -d "/tmp/.X11-unix" ]
do
open -a XQuartz
sleep 5
done

/usr/local/bin/docker run --init --rm --name vivado_container --mount type=bind,source="/tmp/.X11-unix",target="/tmp/.X11-unix" --mount type=bind,source="/Users/tony/arc/pro/dev/vivado4mac",target="/home/user" --platform linux/amd64 x64-linux sudo -H -u user bash /home/user/start_vivado.sh &
osascript -e 'tell app "Terminal" to do script " while ! [[ $(ps aux | grep vivado_container | wc -l | tr -d \"\\n\\t \") == \"1\" ]]; do /Users/tony/arc/pro/dev/vivado4mac/xvcd/bin/xvcd; sleep 1; done; exit"'
