#!/bin/zsh
# change xquartz settings, otherwise no x11 connection from container possible
defaults write org.xquartz.X11 no_auth 1
defaults write org.xquartz.X11 nolisten_tcp 0
defaults write org.nixos.xquartz.X11 no_auth 1
defaults write org.nixos.xquartz.X11 nolisten_tcp 0
# vivado seems to be using glx
defaults write org.xquartz.X11 enable_iglx -bool true
defaults write org.nixos.xquartz.X11 enable_iglx -bool true

open -a XQuartz
orb list

while ! /usr/local/bin/docker ps &>/dev/null; do
  orb restart docker
  sleep 2
done
while ! [ -d "/tmp/.X11-unix" ]; do
  open -a XQuartz
  sleep 1
done

/usr/local/bin/docker run --init --rm --name vivado_container --mount type=bind,source="/tmp/.X11-unix",target="/tmp/.X11-unix" --mount type=bind,source="/Users/tony/arc/pro/dev/vivado4mac",target="/home/user" --platform linux/amd64 x64-linux sudo -H -u user bash /home/user/start_vivado.sh
echo "cleaning up stuff"
# orb stop
osascript -e 'tell application "XQuartz" to quit'
